apiVersion: v1
kind: Service
metadata:
  name: backend-{{ .Values.environment }}
spec:
  selector:
    app: backend-{{ .Values.environment }}
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
