apiVersion: v1
kind: Service
metadata:
  name: frontend-{{ .Values.environment }}
spec:
  selector:
    app: frontend-{{ .Values.environment }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
